services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: carrentaldb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=4DbConec+tion@
    ports:
      - '1433:1433'
    volumes:
      - ./src/infra/database/init.sql:/tmp/init.sql
      - sqlvolume:/var/opt/mssql

  init-db:
    image: mcr.microsoft.com/mssql-tools
    container_name: car-rental-tools
    depends_on:
      - sqlserver
    entrypoint: ["/bin/bash", "-c", "sleep 50s && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P 4DbConec+tion@ -i /tmp/init.sql || exit 1"]
    volumes:
      - ./src/infra/database/init.sql:/tmp/init.sql

volumes:
  sqlvolume:
