services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: carrentaldb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=4DbConec+tion@
    ports:
      - '1433:1433'
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-rental
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - sqlserver
    env_file:
      - .env

volumes:
  sqlvolume: