services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: carrentaldb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=4DbConec+tion@
    ports:
      - '1433:1433'
    volumes:
      - sqlvolume:/var/opt/mssql
      - ./src/infra/config/create-database/init.sql:/var/opt/mssql/init.sql
    command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s & /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 4DbConec+tion@ -d master -i /var/opt/mssql/init.sql"

volumes:
  sqlvolume: